# Generated by Django 6.0.3 on 2026-04-04 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_discount_amount_order_promo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='promo_code',
        ),
    ]
