# Generated by Django 6.0.3 on 2026-04-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Used for calculating profit margin and COGS', max_digits=10, null=True),
        ),
    ]
