# Generated by Django 6.0.3 on 2026-04-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of goods (COGS) per unit. Used for profit margin calculations.', max_digits=10, null=True),
        ),
    ]
