# Generated by Django 6.0.3 on 2026-04-04 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminauditlog',
            name='new_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='old_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='target_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('ROLE_CHANGE', 'Role Change'), ('DEACTIVATE', 'Account Deactivation'), ('REACTIVATE', 'Account Reactivation'), ('STATUS_CHANGE', 'Account Status Change'), ('STOCK_UPDATE', 'Stock Update'), ('OTHER', 'Other Admin Action')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
