# Generated by Django 6.0.3 on 2026-04-04 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_stock_inventoryalert'),
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('subheading', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='promos/')),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('section_type', models.CharField(choices=[('hero', 'Hero Banner'), ('mid_page', 'Mid-Page Section'), ('footer_banner', 'Footer Banner')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='cta_label',
            new_name='cta_text',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='order',
            new_name='display_order',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='secondary_text',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='primary_text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='siteconfig',
            old_name='announcement_active',
            new_name='announcement_is_active',
        ),
        migrations.RenameField(
            model_name='siteconfig',
            old_name='logo',
            new_name='site_logo',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='address',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='announcement_bg_color',
            field=models.CharField(default='#111827', max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='primary_color',
            field=models.CharField(default='#111827', max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='secondary_color',
            field=models.CharField(default='#4b5563', max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='announcement_text',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured_info', to='products.product')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
