# Generated by Django 6.0.3 on 2026-04-04 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_discount_amount_remove_order_promo_code'),
        ('site_config', '0003_promocode_created_by_promocode_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpromousage',
            options={},
        ),
        migrations.AddField(
            model_name='userpromousage',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_usage', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userpromousage',
            name='promo_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='site_config.promocode'),
        ),
    ]
