# Generated by Django 6.0.3 on 2026-04-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0005_heroslide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='PromoSection',
        ),
    ]
